# Generated by Django 5.1.5 on 2025-01-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workorder_number', models.CharField(max_length=50, unique=True)),
                ('part', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('completed_quantity', models.IntegerField(default=0)),
                ('progress', models.DecimalField(decimal_places=1, default=0.0, max_digits=5)),
            ],
        ),
    ]
